package capabilities

// TableRowCount is the number of frozen first-GA capability table rows.
const TableRowCount = 34

// catalog is the frozen first-GA REST↔MCP table. Order is the
// implementation-design capability list; do not reorder or rename in place.
func catalog() []Capability {
	return []Capability{
		{
			ID: HealthLive, Title: "Health live", Version: VersionTag,
			Description: "Process liveness. Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/live"}},
		},
		{
			ID: HealthReady, Title: "Health ready", Version: VersionTag,
			Description: "Snapshot installed and enabled data-plane listeners bound. Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/ready"}},
		},
		{
			ID: VersionGet, Title: "Version", Version: VersionTag,
			Description:    "Build and protocol versions.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Version"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/version"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_version_get"}},
			ServiceMethods: []string{"Version"},
		},
		{
			ID: CapabilitiesGet, Title: "Capabilities", Version: VersionTag,
			Description:    "Capability list and protocol metadata.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "CapabilityView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/capabilities"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_capabilities_get"}, Resources: []string{"labsnmp://capabilities"}},
			ServiceMethods: []string{"Capabilities"},
		},
		{
			ID: StatusGet, Title: "Agent status", Version: VersionTag,
			Description:    "Listeners, revisions, hostTime, and ready.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Status"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/status"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_status_get"}, Resources: []string{"labsnmp://status"}},
			ServiceMethods: []string{"Status"},
		},
		{
			ID: SchemaGet, Title: "Config schema", Version: VersionTag,
			Description:    "Published v1alpha1 config JSON Schema.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/schema/config"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_schema_get"}},
			ServiceMethods: []string{"ConfigSchema"},
		},
		{
			ID: FeaturesList, Title: "Features", Version: VersionTag,
			Description:    "Frozen live vs reset-only catalog.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "FeatureList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/features"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_features_list"}, Resources: []string{"labsnmp://features"}},
			ServiceMethods: []string{"Features"},
		},
		{
			ID: StateGet, Title: "Get state", Version: VersionTag,
			Description:    "Redacted spec plus revision metadata.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "StateView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_state_get"}, Resources: []string{"labsnmp://state"}},
			ServiceMethods: []string{"GetState"},
		},
		{
			ID: StateValidate, Title: "Validate", Version: VersionTag,
			Description:    "Validate a candidate document and/or operations without writing.",
			RequiredScopes: []string{ScopeSNMPAdmin}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ValidateIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:validate"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_state_validate"}},
			ServiceMethods: []string{"Validate"},
		},
		{
			ID: StateExport, Title: "Export", Version: VersionTag,
			Description:    "Canonical desired-state export plus drift material.",
			RequiredScopes: []string{ScopeSNMPAdmin}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Export"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state:export"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_state_export"}},
			ServiceMethods: []string{"Export"},
		},
		{
			ID: StateReset, Title: "Reset", Version: VersionTag,
			Description:    "Reread the bootstrap mount, drop overlay, wipe traps and queries, and swap. Never writes the file.",
			RequiredScopes: []string{ScopeSNMPAdmin}, Mutating: true,
			InputSchema:    &SchemaRef{Name: "ResetIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:reset"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_state_reset"}},
			ServiceMethods: []string{"Reset"},
		},
		{
			ID: ChangesPlan, Title: "Plan", Version: VersionTag,
			Description:    "Dry-run operations against the active snapshot.",
			RequiredScopes: []string{ScopeSNMPAdmin}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:plan"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_change_plan"}},
			ServiceMethods: []string{"Plan"},
		},
		{
			ID: ChangesApply, Title: "Apply", Version: VersionTag,
			Description:    "Apply operations. expectedRevision is required.",
			RequiredScopes: []string{ScopeSNMPAdmin}, Mutating: true, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:apply"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_change_apply"}},
			ServiceMethods: []string{"Apply"},
		},
		{
			ID: SessionCreate, Title: "Create session", Version: VersionTag,
			Description: "Cookie + CSRF session for the operator UI. Accepts bearer.",
			Idempotent:  false, RESTOnly: true, Mutating: true,
			REST: []RESTBinding{{Method: "POST", Path: "/v1/session"}},
		},
		{
			ID: SessionGet, Title: "Get session", Version: VersionTag,
			Description: "Current session principal (cookie or bearer).",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/session"}},
		},
		{
			ID: SessionDelete, Title: "Delete session", Version: VersionTag,
			Description: "Clear the operator UI session cookie.",
			Idempotent:  true, RESTOnly: true, Mutating: true,
			REST: []RESTBinding{{Method: "DELETE", Path: "/v1/session"}},
		},
		{
			ID: MapsList, Title: "List maps", Version: VersionTag,
			Description:    "List named OID maps.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "MapList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/maps"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_maps_list"}, Resources: []string{"labsnmp://maps"}},
			ServiceMethods: []string{"ListMaps"},
		},
		{
			ID: MapsGet, Title: "Get map", Version: VersionTag,
			Description:    "Get one named OID map.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "MapSpec"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/maps/{name}"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_map_get"}, Resources: []string{"labsnmp://maps/{name}"}},
			ServiceMethods: []string{"GetMap"},
		},
		{
			ID: MapsQuery, Title: "Query map", Version: VersionTag,
			Description:    "Simulate GET/GETNEXT/GETBULK against a named map without sending a datagram.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "MapQueryIn"},
			OutputSchema:   &SchemaRef{Name: "MapQueryResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/maps/{name}:query"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_map_query"}},
			ServiceMethods: []string{"QueryMap"},
		},
		{
			ID: OIDsSet, Title: "Set OID", Version: VersionTag,
			Description:    "Write one overlay value. Same overlay as SNMP SET. Body is a single {oid, value}.",
			RequiredScopes: []string{ScopeSNMPWrite}, Mutating: true,
			InputSchema:    &SchemaRef{Name: "OIDSetIn"},
			OutputSchema:   &SchemaRef{Name: "OIDResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/maps/{name}/oids:set"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_oid_set"}},
			ServiceMethods: []string{"SetOID"},
		},
		{
			ID: OIDsGet, Title: "Get OID", Version: VersionTag,
			Description:    "Read one oid from a named map plus overlay.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "OIDGetIn"},
			OutputSchema:   &SchemaRef{Name: "OIDResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/maps/{name}/oids:get"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_oid_get"}},
			ServiceMethods: []string{"GetOID"},
		},
		{
			ID: QueriesList, Title: "Query log", Version: VersionTag,
			Description:    "Last-N PDU ring (request type, identity, decision, error status).",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "QueryList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/queries"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_queries_list"}, Resources: []string{"labsnmp://queries"}},
			ServiceMethods: []string{"ListQueries"},
		},
		{
			ID: PreviewGet, Title: "Preview GET", Version: VersionTag,
			Description:    "Evaluate a community or user plus oid against the compiled tree without a wire packet.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "OIDResult"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/preview/get"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_preview_get"}},
			ServiceMethods: []string{"Preview"},
		},
		{
			ID: CommunitiesList, Title: "List communities", Version: VersionTag,
			Description:    "List communities. Wire strings never appear; communityFile paths may.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "CommunityList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/communities"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_communities_list"}},
			ServiceMethods: []string{"ListCommunities"},
		},
		{
			ID: UsersList, Title: "List users", Version: VersionTag,
			Description:    "List v3 users. Secret bytes never appear; secretFile paths may.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "UserList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/users"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_users_list"}},
			ServiceMethods: []string{"ListUsers"},
		},
		{
			ID: TrapsList, Title: "List traps", Version: VersionTag,
			Description:    "List the ephemeral trap/inform inbox.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "TrapList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/traps"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_traps_list"}, Resources: []string{"labsnmp://traps"}},
			ServiceMethods: []string{"ListTraps"},
		},
		{
			ID: TrapsGet, Title: "Get trap", Version: VersionTag,
			Description:    "Get one trap/inform by ULID.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "TrapRecord"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/traps/{id}"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_trap_get"}, Resources: []string{"labsnmp://traps/{id}"}},
			ServiceMethods: []string{"GetTrap"},
		},
		{
			ID: TrapsRaw, Title: "Get trap raw", Version: VersionTag,
			Description:    "Get the retained trap/inform datagram.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/traps/{id}/raw"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_trap_raw_get"}},
			ServiceMethods: []string{"GetTrapRaw"},
		},
		{
			ID: TrapsWait, Title: "Wait traps", Version: VersionTag,
			Description:    "Wait for an existing or later matching trap. wait_timeout or store_wiped.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "TrapWaitIn"},
			OutputSchema:   &SchemaRef{Name: "TrapRecord"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/traps:wait"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_traps_wait"}},
			ServiceMethods: []string{"WaitTraps"},
		},
		{
			ID: TrapsClear, Title: "Clear traps", Version: VersionTag,
			Description:    "Wipe the trap inbox. Waiters receive store_wiped.",
			RequiredScopes: []string{ScopeSNMPWrite}, Mutating: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/traps:clear"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_traps_clear"}},
			ServiceMethods: []string{"ClearTraps"},
		},
		{
			ID: StatsGet, Title: "Stats", Version: VersionTag,
			Description:    "Trap store occupancy, overlay generation, and query ring length.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Stats"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/stats"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_stats_get"}, Resources: []string{"labsnmp://stats"}},
			ServiceMethods: []string{"Stats"},
		},
		{
			ID: AuditList, Title: "Audit list", Version: VersionTag,
			Description:    "Query recent in-memory audit events.",
			RequiredScopes: []string{ScopeSNMPAuditRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "AuditList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_audit_query"}},
			ServiceMethods: []string{"QueryAudit"},
		},
		{
			ID: AuditGet, Title: "Audit get", Version: VersionTag,
			Description:    "Get one audit event by ID.",
			RequiredScopes: []string{ScopeSNMPAuditRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "AuditEvent"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit/{id}"}},
			MCP:            &MCPBinding{Tools: []string{"snmp_audit_get"}},
			ServiceMethods: []string{"GetAudit"},
		},
		{
			ID: MetricsGet, Title: "Metrics", Version: VersionTag,
			Description:    "OpenMetrics text. Served only when observability.metrics.publicPath is true.",
			RequiredScopes: []string{ScopeSNMPRead}, Idempotent: true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/metrics"}},
		},
	}
}
